services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    volumes:
      - ./data:/usr/src/app/data
      - ./notebook:/usr/src/app/notebook
      - ./job:/usr/src/app/job
      - ./output:/usr/src/app/output
